naam = input("je naam? ")
leeftijd = input("hoe oud ben je? ")
woonplaats = input("waar woon je? ")
afstand = input("hoe ver is dat van school? ")
zelf = input("vul wat van jezelf in, dus het begint met ik: ")
print()
print("hallo mijn naam is "+ naam + " en ik ben " + leeftijd + " jaar oud. ik woon in " + woonplaats + " en dat is " + afstand + "km van school vandaan.")
print("ik "+zelf)