answer = input("player number?")
print("")
if answer.lower() == "1":
     print ("name: Erwin Henraat")
     print ("special power: superstrength")
     print ("speed: 90")
     print ("health: 240")
     print ("vehicle: Seat Arona 1.0 TSI FR")
     print ("weapon: mp5")
     print ("level: 90")
     print ("wanted: True")
elif answer.lower() == "2":
     print ("name: Edgar Rikkert")
     print ("special power: regeneration")
     print ("speed: 125")
     print ("health: 175")
     print ("vehicle: Triumph TIGER 660")
     print ("weapon: kris vector")
     print ("level: 43")
     print ("wanted: True")
elif answer.lower() == "3":
     print ("name: Odin Schaaphok")
     print ("special power: pyromagic")
     print ("speed: 145")
     print ("health: 120")
     print ("vehicle: Argo 8X8 700 HD")
     print ("weapon: akimbo .357 revolvers")
     print ("level: 50")
     print ("wanted: True")
elif answer.lower() == "4":
     print ("name: Beert Kleppe")
     print ("special power: intimidation")
     print ("speed: 50")
     print ("health: 310")
     print ("vehicle: Lexus LFA")
     print ("weapon: glock 18")
     print ("level: 138")
     print ("wanted: false")
elif answer.lower() == "5":
     print ("name: Tolgahan van der Weiden")
     print ("special power: exccelent sneek")
     print ("speed: 150")
     print ("health: 100")
     print ("vehicle: none")
     print ("weapon: suppressed Orsis T-5000")
     print ("level: 67")
     print ("wanted: True")
elif answer.lower() == "6":
     print ("name: Helène Rijks")
     print ("special power: seduction")
     print ("speed: 140")
     print ("health: 145")
     print ("vehicle: Kawasaki EX300 NINJA 300 ABS")
     print ("weapon: Ballistic knife")
     print ("level: 78")
     print ("wanted: True")